# Application Configuration
spring.application.name=ticket-management-system
spring.profiles.active=dev

aws.cognito.userPoolId=us-west-2_E1RNszQIj
aws.cognito.clientId=68qpp26q54e3qqchtf05rqajhk
aws.cognito.region=us-west-2


